# Main app stacked widget (login, home, play movie, read book) indexes
HOME_SCREEN_INDEX = 0
ADD_MEDIA_SCREEN_INDEX = 1
MANAGE_MEDIA_SCREEN_INDEX = 2

# Home screen stacked widget indexes
MOVIE_SELECTION_SCREEN_INDEX = 0
MUSIC_SELECTION_SCREEN_INDEX = 1
BOOK_SELECTION_SCREEN_INDEX = 2
SETTINGS_SCREEN_INDEX = 3

# Tab Widget Indexes
LIBRARY_INDEX = 0
PLAYLISTS_INDEX = 0